### ISSUE TITLE
Don't use class instance variable example.  Use a factory methods example.

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/ruby-object-class-methods#19]
This could be  `Album#search` or some such that returns an array of Album instances which match a title for artist search.

**Comment by jrhorn424** [comment]
@gaand By this, did you mean not to every use class instance variables, or to only use them for factory methods?

**Comment by jrhorn424** [comment]
I ask because #20 brings it up, and the linter (and the community) prefer class instance variables to instance variables.
