### ISSUE TITLE
@@cats_count in cat_counter.rb

### ISSUE THREAD

**Issue by raq929** [ga-wdi-boston/ruby-object-class-methods#20]
The linter doesn't like this. It thinks I should replace the class var with a class instance var. But I'm teaching class vars. 

I don't like having linter errors, but I'm not sure how to avoid this one. Ideas?

**Comment by raq929** [comment]
Possibly related to #19?

**Comment by jrhorn424** [comment]
Use a class instance var? What's your objection? No need to do it this time.

**Comment by jrhorn424** [comment]
You're correct. The whole example should be waxed per #19. But to illustrate my previous comment:

```diff
class Cat
-  @@cats_count = 0
+  @cats_count = 0

  def initialize(name)
    @name = name
-    @@cats_count += 1
+    @cats_count += 1
+    # or maybe self.instance_variable_get(:@cats_count) += 1
  end

  def self.cats_count
-    @@cats_count
+    @cats_count
+    # or maybe self.instance_variable_get(:@cats_count)
  end

  def meow
    puts "#{@name} meows"
  end
end
```

**Comment by jrhorn424** [comment]
I see `cat_counter.rb` is gone. Is this closeable, @raq929?

**Comment by jrhorn424** [comment]
https://www.commandercoriander.net/blog/2013/05/08/a-note-on-class-variables/

**Comment by MicFin** [comment]
`cat_counter.rb` is gone and there are no class variables in repo `@@`.  This can be closed @jrhorn424.

**Comment by gaand** [comment]
\o/

Also, yay!
