### ISSUE TITLE
Why were these requirements excluded from the Album/Song example?

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/ruby-object-class-methods#23]
I'd like to discuss the reason I had them in there in the first place.

- https://github.com/ga-wdi-boston/ruby-object-class-methods/commit/8fb9bd619fff2170e0572df65e27025bbce19009#diff-28b2173d51b03fc4711e8b79af5e0c38L4
- https://github.com/ga-wdi-boston/ruby-object-class-methods/commit/8fb9bd619fff2170e0572df65e27025bbce19009#diff-28b2173d51b03fc4711e8b79af5e0c38L15
- https://github.com/ga-wdi-boston/ruby-object-class-methods/commit/8fb9bd619fff2170e0572df65e27025bbce19009#diff-28b2173d51b03fc4711e8b79af5e0c38L26

**Comment by jrhorn424** [comment]
I see. I think the requirements were lost because they weren't included in the list for Lab, or they were included in a funny/unclear way:

>Use this class method to set YOUR favorite Album by searching for the album title.

**Comment by jrhorn424** [comment]
Possibly reopen #15?

**Comment by raq929** [comment]
Oh! No, they weren't included because we're not using class instance variables any more (per @gaand), so the albums array has to be immutable. 
I'd love to chat about this more.

**Comment by gaand** [comment]
Since ruby has become threaded, access to anything not an instance variable or immutable should be guarded by mutexes.  Since delving into this area is well beyond the scope of WDI, I believe it's probably best to exclude it.

**Comment by jrhorn424** [comment]
Thanks @gaand!
